# Use Python base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy backend files
COPY . .

# Install Flask and other Python dependencies
RUN pip install -r requirements.txt

# Run Flask API
CMD ["python", "app.py"]
