version: '3.8'

services:
  blockchain:
    build:
      context: ./blockchain
      dockerfile: Dockerfile.blockchain
    ports:
      - "8545:8545"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backends
    ports:
      - "5000:5000"
    depends_on:
      - blockchain
