version: "3.8"

services:
  blockchain:
    build: ./docker/Dockerfile.blockchain
    ports:
      - "8545:8545"
  
  backend:
    build: ./docker/Dockerfile.backend
    volumes:
      - ./backend:/app
    environment:
      - INFURA_PROJECT_ID=${INFURA_PROJECT_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    depends_on:
      - blockchain
