# Use Node.js image
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy files from the blockchain folder
COPY . .

# Install Hardhat and dependencies
RUN npm install

# Start Hardhat local blockchain
CMD ["npx", "hardhat", "node"]
